### ISSUE TITLE
Reasons for changing default citation key format?

### ISSUE THREAD

**Issue by orschiro** [bbest/rmarkdown-example#2]
Dear @bbest,

I am so grateful having found your repository! At the moment, this is helping me a lot moving my entire writing to Rmarkdown. 

I have one question: Why do you recommend changing the default citation key format here:

![image](https://cloud.githubusercontent.com/assets/170947/10119243/37208e20-6490-11e5-96d8-be17bacb1d00.png)

Thankfully,

Robert

**Comment by bbest** [comment]
Hi Robert,

Just trying to match the expected format by pandoc.

Hope that makes sense, Ben

**Comment by orschiro** [comment]
@bbest,

Alright, thanks! :+1: 

~ Robert
